[tool.poetry]
name = "plan-b"
version = "0.1.0"
description = ""
authors = ["Nat Hillard <nathaniel.hillard@va.gov>", "Aaron Houlihan <aaron@amida.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
boto3 = "^1.17.75"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
