AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  VroPdfGeneratorLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: vro--wkhtmltopdf/
      Description: PDF Generator library - wkhtmltopdf
      LayerName: vro--pdf-generator-layer

  VroPythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: vro--python-dependencies-layer
      Description: Python Dependencies for VroMainFunction
      LayerName: vro--python-dependencies-layer
    Metadata:
      BuildMethod: python3.8
