Transform: AWS::Serverless-2016-10-31

Description: >
  Plan C

  Using AWS Secrets Manager with Lambda

Parameters:
  LighthouseTokenUrl:
    Type: String
  LighthouseClientId:
    Type: String
  LighthouseJwtAud:
    Type: String
  LighthousePrivateRsaKey:
    Type: String
  KmsCmkId: 
    Type: String

Resources:
  vroLambda:
    Type: AWS::Serverless::Function
    Description: "test description"
    Properties:
      Handler: lambdaHandler.handler
      Runtime: nodejs14.x
      CodeUri: lambdaFunction/
      Environment:
        Variables:
          LH_TOKEN_URL: !Ref LighthouseTokenUrl
          LH_CLIENT_ID: !Ref LighthouseClientId
          LH_JWT_AUD: !Ref LighthouseJwtAud
            # # TODO: Cleanup this comment: For some reason !GetAtt vroLhPrivateRsaKey.Arn doesnt work. I would think this should work.
          LH_PRIVATE_RSA_KEY_SECRET_ARN: !Ref vroLhPrivateRsaKey
      Role: !GetAtt vroLambdaExecutionRole.Arn

  vroLhPrivateRsaKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "VBA Virtual Regional Office: Your RSA private key to access Lighthouse APIs via the Client Credentials OAuth grant type"
      SecretString:
        Ref: LighthousePrivateRsaKey
      # KmsKeyId: KmsCmkId

  vroLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'vro-lambda-execution-role'
      # "Allows Lambda to assume this role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            # TODO: Limit this down. Allowing all lambda to assume this role is too much. Limit it
            # to just the ARN of your lambda function.
            Principal:
              Service:
                - "lambda.amazonaws.com"
      # TODO: Cleanup this comment: It's unfortunate that they use the word "Role" in the name, because it's actually a policy.
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "vroLambdaSecretsManagerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: !Ref vroLhPrivateRsaKey
