AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  hypertension-decider

  App to take CDW medical data as input and decide on appropriate disability grade

Parameters:
  LighthouseTokenUrl:
    Type: String
  LighthouseClientId:
    Type: String
  LighthouseJwtAud:
    Type: String
  LighthousePrivateRsaKey:
    Type: String
  KmsCmkId: 
    Type: String

Resources:
  VroMainFunction:
    Type: AWS::Serverless::Function
    Description: "test description"
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          LH_TOKEN_URL: !Ref LighthouseTokenUrl
          LH_CLIENT_ID: !Ref LighthouseClientId
          LH_JWT_AUD: !Ref LighthouseJwtAud
            # # TODO: Cleanup this comment: For some reason !GetAtt VroLhPrivateRsaKey.Arn doesnt work. I would think this should work.
          LH_PRIVATE_RSA_KEY_SECRET_ARN: !Ref VroLhPrivateRsaKey
      Role: !GetAtt VroLambdaExecutionRole.Arn

  VroLhPrivateRsaKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "VBA Virtual Regional Office: Your RSA private key to access Lighthouse APIs via the Client Credentials OAuth grant type"
      SecretString:
        Ref: LighthousePrivateRsaKey
      KmsKeyId: !Ref KmsCmkId

  VroLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'vro-lambda-execution-role'
      # "Allows Lambda to assume this role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            # TODO: Limit this down. Allowing all lambda to assume this role is too much. Limit it
            # to just the ARN of your lambda function.
            Principal:
              Service: "lambda.amazonaws.com"
      # TODO: Cleanup this comment: It's unfortunate that they use the word "Role" in the name, because it's actually a policy.
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "VroLambdaSecretsManagerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "secretsmanager:GetSecretValue"
                Resource: !Ref VroLhPrivateRsaKey
              - Effect: "Allow"
                Action: "kms:Decrypt"
                Resource: "*"
