AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  hypertension-decider

  App to take CDW medical data as input and decide on appropriate disability grade

Resources:
  HypertensionMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PdfGeneratorLayer
      Environment: 
        Variables:
          FONTCONFIG_PATH: /opt/fonts
      Events:
        HelloWorld:
          # If you `sam deploy` this (not intend, given that this file is intended for local dev
          # only), it will actually create an API Gateway API
          # More info about API Event Source:
          # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            Path: /
            Method: get

  PdfGeneratorLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: layer/.
      Description: PDF Generator binary - wkhtmltopdf
      LayerName: pdf-generator-layer
    # Metadata:
    #   BuildMethod: makefile
